# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.228
neo_version_range=[21,)
loader_version_range=[4,)

## Mod Properties
mod_id=invasiveopts
mod_name=Invasive Optimizations
mod_license=MIT
mod_version=1.0.22
mod_group_id=dev.qther
mod_authors=Qther
mod_description=Invasive optimizations for other mods. If you experience any issues, disable this mod first!

## Dependency Properties

# https://maven.fallenbreath.me/#/releases/me/fallenbreath/conditional-mixin-neoforge
conditional_mixin_version=0.6.4
# https://github.com/Bawnorton/MixinSquared
mixin_squared_version=0.3.7-beta.2

# https://maven.blamejared.com/net/darkhax/botanypots/botanypots-neoforge-1.21.1/
botanypots_version=21.1.41
botanypots_version_range=[21.1,21.2)

# https://maven.blamejared.com/net/darkhax/bookshelf/bookshelf-neoforge-1.21.1/
bookshelf_version=21.1.81

# https://modmaven.dev/mekanism/Mekanism/
mekanism_version=1.21.1-10.7.18.84
mekanism_version_range=[10.7.0,)

# https://modrinth.com/mod/pipez/versions
pipez_version=neoforge-1.21.1-1.2.31
pipez_version_range=[1.2.31,)

# https://www.curseforge.com/minecraft/mc-mods/xycraft/files/all
xycraft_core_version=6872525
xycraft_core_version_range=[0.7.53,)

# https://www.curseforge.com/minecraft/mc-mods/xycraft-world/files/all
xycraft_world_version=6872532
xycraft_world_version_range=[0.7.53,)

# https://www.curseforge.com/minecraft/mc-mods/xycraft-machines/files/all
xycraft_machines_version=6872530
xycraft_machines_version_range=[0.7.53,)

# https://modrinth.com/mod/pastel/versions
pastel_version=1.1.5.5
pastel_version_range=[1.1.5.5,)

# https://maven.createmod.net/com/simibubi/create/create-1.21.1/
create_version = 6.0.10-280
create_version_range = [6.0.10,)
# https://mvn.devos.one/#/snapshots/com/tterrag/registrate/Registrate
registrate_version = MC1.21-1.3.0+67
# https://maven.createmod.net/dev/engine-room/flywheel/flywheel-neoforge-1.21.1/
flywheel_version = 1.0.6
# https://maven.createmod.net/net/createmod/ponder/Ponder-NeoForge-1.21.1/
ponder_version = 1.0.82

# https://maven.wispforest.io/#/releases/io/wispforest/owo-lib/
owo_version=0.13.0-alpha.15+1.21
# owo_version_range=[0.13.0-alpha,)
# https://maven.wispforest.io/#/releases/io/wispforest/accessories-neoforge
accessories_version=1.1.0-beta.53+1.21.1
accessories_version_range=[1.1.0-beta,)

# https://central.sonatype.com/artifact/org.appliedenergistics/appliedenergistics2/versions
ae2_version=19.2.17
ae2_version_range=[19.2.17,)

# https://maven.shadowsoffire.dev/#/releases/dev/shadowsoffire/Placebo
placebo_version=9.9.1
placebo_version_range=[9.9.0,)

# https://www.curseforge.com/minecraft/mc-mods/super-factory-manager/files/all?page=1&pageSize=20&showAlphaFiles=show
sfm_version=8370241
sfm_version_range=[4.30.0,]
