modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL="https://github.com/Vonr/invasiveopts/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/Vonr/invasiveopts"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "SERVER"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "SERVER"

[[dependencies."${mod_id}"]]
modId="botanypots"
type="optional"
versionRange="${botanypots_version_range}"
ordering="AFTER"
side="BOTH"
[dependencies."${mod_id}".mc-publish]
modrinth = "botany-pots"
curseforge = "botany-pots"

[[dependencies."${mod_id}"]]
modId="pipez"
type="optional"
versionRange="${pipez_version_range}"
ordering="AFTER"
side="BOTH"
[dependencies."${mod_id}".mc-publish]
modrinth = "pipez"
curseforge = "pipez"

[[dependencies."${mod_id}"]]
modId="mekanism"
type="optional"
versionRange="${mekanism_version_range}"
ordering="AFTER"
side="BOTH"
[dependencies."${mod_id}".mc-publish]
modrinth = "mekanism"
curseforge = "mekanism"

[[dependencies."${mod_id}"]]
modId="xycraft_machines"
type="optional"
versionRange="${xycraft_machines_version_range}"
ordering="AFTER"
side="BOTH"
[dependencies."${mod_id}".mc-publish]
# modrinth = "xycraft-machines"
curseforge = "xycraft-machines"
